INSERT INTO FRIENDSHIP (friendship_id, status) VALUES (1, 'CONFIRMED');
INSERT INTO FRIENDSHIP (friendship_id, status) VALUES (2, 'UNCONFIRMED');

INSERT INTO RATING_MPA (RATING_MPA_ID, NAME) values (1, 'G');
INSERT INTO RATING_MPA (RATING_MPA_ID, NAME) values (2, 'PG');
INSERT INTO RATING_MPA (RATING_MPA_ID, NAME) values (3, 'PG-13');
INSERT INTO RATING_MPA (RATING_MPA_ID, NAME) values (4, 'R');
INSERT INTO RATING_MPA (RATING_MPA_ID, NAME) values (5, 'NC-17');

INSERT INTO GENRE (GENRE_ID, NAME) VALUES (1, 'Комедия');
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (2, 'Драма');
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (3, 'Мультфильм');
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (4, 'Триллер');
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (5, 'Документальный');
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (6, 'Боевик');




